#!/bin/bash
CONFIGURATION="olp_lib_tests.xml";

if test -z "$1"; then
    phpunit --configuration $CONFIGURATION
    exit 0;
fi

COVERAGE="";

if test "$1"="-c"; then
    if test -n "$2"; then
        COVERAGE="--coverage-html $2";
    fi
fi

phpunit $COVERAGE --configuration $CONFIGURATION
