<?php

/**
 * Failure reason generated by an {@see OLPBlackbox_Rule_ExcludedStates} failure.
 *
 * @package OLPBlackbox
 * @subpackage FailureReasons
 * @author Dan Ostrowski <dan.ostrowsk@sellingsource.com>
 */
class OLPBlackbox_FailureReason_ExcludedStates extends OLPBlackbox_FailureReason
{
	/**
	 * @param array $excluded_states List of states which could not be lent to.
	 * @param string $reported_state State which was reported by the user.
	 */
	public function __construct(array $excluded_states, $reported_state)
	{
		$this->data['excluded_states'] = $excluded_states;
		$this->data['reported_state'] = $reported_state;
	}
	/**
	 * Generates a human readable representation of this failure reason.
	 *
	 * @return string
	 */
	public function getDescription()
	{
		// If, for sure nothing depends on this message being verbatim from 
		// legacy blackbox (2) this could be made more specific, example: 
		// return sprintf('State "%s" is not allowed.', $this->reported_state);
		return 'React changed state to disallowed state.';
	}
}

?>
