<?php 

/**
 * This file was automatically generated by generate_writable_model.php
 * at 2009-10-29, 09:05:05 from 'mysql:host=monster.tss;port=3326;dbname=olp'.
 *
 * NOTE: Modifications to this file will be overwritten if/when
 * it is regenerated.
 * 
 * Seriously consider modifying OLP_Models_BlackboxPostData instead. There's a 
 * sister class OLP_Models_BlackboxPostDataSent that should have the same functionality
 * really.
 * @author Stephan Soileau <stephan.soileau@sellingsource.com>
 */
class OLP_Models_BlackboxPostDataReceived extends OLP_Models_BlackboxPostData   
{

	/**
	 * Returns the column this table stores it's post
	 * data in
	 * @return string
	 */
	protected function getDataColumn()
	{
		return 'data_received';
	}

	/**
	 * An array of the columns that comprise the primary key
	 * @return array string[]
	 */
	public function getPrimaryKey()
	{
		return array('blackbox_post_data_sent_id');
	}

	/**
	 * The auto increment column, if any
	 * @return string|void
	 */
	public function getAutoIncrement()
	{
		return 'blackbox_post_data_sent_id';
	}

	/**
	 * Indicates the table name
	 * @return string
	 */
	public function getTableName()
	{
		return 'blackbox_post_data_received';
	}

}
