<?php
	// ======================================================================
	// Affinity Direct Educational Leads
	// This is an extension of the batch.nightly.page2drops.php 
	// TmpTable0434 must be populated 
	//
	// Most of the code was lifted from a file generated by DataGrabber(tm)
	// myya.perez@thesellingsource.com 04-11-2005
	// ======================================================================
	
	
	// INCLUDES / DEFINES / INITIALIZE VARIABLES
	// ======================================================================

	require_once('mysql.3.php');
	require_once('csv.1.php');
	require_once('hit_stats.1.php');
	require_once("prpc/client.php");
	require_once("HTTP/Request.php");
	require_once("ftp.2.php");

	define('LICENSE_KEY',  '3301577eb098835e4d771d4cceb6542b');
	define('STAT_COL', 'h7');	
	
	$csv_records = array();
	$today = date("Y-m-d");
	
	
	// SQL CONNECT & QUERY
	// ======================================================================		
	
	$sql=new MySQL_3();
	$sql->connect("both","selsds001","sellingsource","%selling\$_db");

	$query = 
	"
		SELECT 
			* 
		FROM 
			TmpTable0434 
		LIMIT 
			2000
	";

	$result = $sql->query("lead_generation", $query);
	
	$result_count = $sql->Row_Count($result);
	print "\r\nResult Count - ".$result_count."\r\n";

	// CREATE_CSV
	//============================================================	

	$fields = array
	(
		 "referId"
		,"campaignId"
		,"dphone"
		,"nphone"
		,"fname"
		,"lname"
		,"address1"
		,"address2"
		,"city"
		,"state"
		,"zip"
		,"emailaddress"
		,"SSN"
		,"signup_source"
		,"timestamp"
	);
	
	$path = "/tmp/";
	$filename = "AFF_DIR_EDU_".$today;
	$csvfile = $filename.".csv";
	$path_to_csvfile = $path . $csvfile;

	$fp = fopen($path_to_csvfile, "w")
		or die("cannot open csv");
		
	$csv = new CSV
	(
		array
		(
			"flush" 		=> false, 
			"stream" 		=> $fp, 
			"forcequotes" 	=> true, 
			"header"		=> $fields
		)
	);
	
	while ($row = $sql->Fetch_Array_Row($result))
	{
		$csv_array = array
		(
			"PW601"
			,"1"
			,'='.$dphone = str_replace("-", "", $row['work_phone'])
			,'='.$nphone = str_replace("-", "", $row['home_phone'])
			,'='.$fname = strtoupper($row['first_name'])
			,'='.$lname = strtoupper($row['last_name'])
			,$address = strtoupper($row['address_1'])
			,""
			,'='.$city = strtoupper($row['city'])
			,'='.$state = strtoupper($row['state'])
			,'='.$row['zip']
			,'='.$email = strtoupper($row['email'])
			,'='.$row['ssn']
			,'='.$row['signup_source']
			,'='.$row['created']
		);

		$csv->recordFromArray($csv_array);
	}
	
	$csv->_buf = str_replace('"=','="',$csv->_buf);
	$mycsv = $csv->_buf;
	$csv->flush();
	
	
	// FTP
	//============================================================	

		$ftp_client = new FTP();
		$ftp_client->server 	= "ftp.sellingsource.com";
		$ftp_client->user_name 	= "affinitydirect";
		$ftp_client->user_password = "password";		
		$ftp_client->do_Connect($ftp_client);
		$ftp_client->file = "$path_to_csvfile,/$csvfile";
		$ftp_client->put_File($ftp_client->file,true);

		
	// SEND_EMAIL FUNCTION
	//============================================================		
	
	function send_email($csv, $count, $date)
	{	
	
		$header = (object)array
		(
			"port"			 => 25,
			"url"			 => "maildataserver.com",
			"subject"		 => "Affinity Direct Edu Leads",
			"sender_name"	 => "John Hawkins",
			"sender_address" => "john.hawkins@thesellingsource.com"
		);
		
	 	$recipient = array
	 	(
	 		//(object)array("type" => "to", "name" => "Ken Keyes",  "address" => "kkeyes@addictivemarketing.com"),
			//(object)array("type" => "to", "name" => "Laura G.",   "address" => "laura.gharst@partnerweekly.com"),
			(object)array("type" => "to", "name" => "Programmer", "address" => "myya.perez@thesellingsource.com"),
	 	);	
		
		$message = (object)array
		(
			"text" => "Please see attached CSV file. There are $count records..."
		);
			
		$attach = new stdClass ();
		$attach->name = "AFF_DIR_EDU_".$date.".csv";
		$attach->content = base64_encode ($csv);
		$attach->content_type = "text/csv";
		$attach->content_length = strlen ($csv);
		$attach->encoded = "TRUE";		
		
		$mail = new Prpc_Client("prpc://smtp.2.soapdataserver.com/smtp.1.php");
		$mail_id = $mail->CreateMailing("AFF_DIR_EDU", $header, NULL, NULL);
		$package_id = $mail->AddPackage($mail_id, $recipient, $message, array ($attach));
		$sender = $mail->SendMail($mail_id);	
	
		print "\r\nEMAILS HAVE BEEN SENT.\r\n";
	}		

	send_email ($mycsv, $result_count, $today);
		
	Hit::Stats_Promoless(LICENSE_KEY, $sql, STAT_COL, $result_count);

	print "\r\rDONE AND DONE\r\r";

?>