<?php

	/***
	
		batch.nightly.datran.funded.php
		--
		each night, grab from the various olp_* databases
		all newly funded applicants.. and send them to Datran
		
	***/
	
	require_once('mysql.3.php');
	require_once('debug.1.php');
	require_once('error.2.php');
	
	require_once('csv.1.php');	
	
	
	define('DEBUG_MODE', FALSE);
	
	// Main Object
	class Datran
	{
		// static //
		function Send($data_array,$debugmode=FALSE)
		{
			$data = array();
			$data['p'] = "SELFUN";
            $data['d'] = "http://www." . $data_array['url'];
			$data['f'] = $data_array['first_name'];
			$data['l'] = $data_array['last_name'];
			$data['e'] = $data_array['email'];
			$data['IP']= $data_array['ip_address'];
			$data['a'] = $data_array['address_1'];
            $data['c'] = $data_array['city'];
            $data['s'] = $data_array['state'];
            $data['z'] = $data_array['zip'];
            $data['t'] = $data_array['home_phone'];
			

					
			$vals = array();
			
			// format
			foreach ($data as $key=>$value) {
				$vals[] = $key."=".urlencode($value);
			}
			
			// our get string!!!1111one
			$get = "http://selsc.superautoresponders.com/c.aspx?" . join('&', $vals);
			
			// dont send this to datran, its a test!
			if ( $debugmode === FALSE )
				$response = file($get);
			else return $get;


			// Success! :D
			return TRUE;
		}
	}

	$days = date ( "Ymd000000", strtotime("-60 days") );
	$start = date ( "Ymd000000", strtotime("-1 days") );
	$end = date ( "Ymd235959", strtotime("-1 days") );
	
	
	
	$sql = new MySQL_3();
	$x = $sql->connect(NULL, "selsds001", "sellingsource", "%selling\$_db", Debug_1::Trace_Code(__FILE__,__LINE__));
	
	Error_2::Error_Test($x, TRUE);
	
	
	
	$DBS = array("olp_ucl_visitor", "olp_ufc_visitor",  "olp_ca_visitor", "olp_d1_visitor", "olp_pcl_visitor");
	$fp = fopen("/tmp/dtrn_selfun_{$start}_{$end}.csv","w");
	
	$CSV = new CSV(
			array(
			"forcequotes" => TRUE,
			"header" => array("FIRST_NAME","LAST_NAME","EMAIL","HOME_PHONE","ADDRESS_1","CITY","STATE","ZIP","IP_ADDRESS"),
			"stream" => $fp,
			"flush" => FALSE));
	

	
	
	$total_count = 0;
	
	foreach ( $DBS as $db ) 
	{
		$count = 0;
		$q = 
			"
			SELECT
				personal.first_name,
				personal.last_name,
				personal.email,
				personal.home_phone,
				residence.address_1,
				residence.city,
				residence.state,
				residence.zip,
				campaign_info.ip_address,
				campaign_info.url,
			FROM application
			JOIN residence USING (application_id)
			JOIN personal USING (application_id)
			JOIN campaign_info USING (application_id)
			JOIN stat_info USING (application_id)
			WHERE application.created_date > '$days'
			AND stat_info.funded between '$start' and '$end'
			and campaign_info.ip_address != ''";
		
		$rs = $sql->query($db, $q, Debug_1::Trace_Code(__FILE__,__LINE__));
		
		Error_2::Error_Test($rs, TRUE);
		
		
		
		
		while ( $row = $sql->Fetch_Object_Row($rs) )
		{ // debug info
			$count++;
			print "\n\nDATRAN_START";
			print "\n$db - $count";
			$CSV->recordFromArray ( (array)$row );
			
			print Datran::Send((array)$row, DEBUG_MODE);
			print "\nDATRAN_END";
		}
		
		$total_count += $count;
	}
			
			
	$CSV->flush();
	print "\n\nTOTAL : $total_count \n";
	
	
	
					$message = new StdClass ();
					$message->text = "
					
					DataGrubber Run #		
					
					$total_count records were sent to datran
					
					 This is an automatic email generated by TSSDataGrubber; do not reply.  If you have any questions, please contact john.hargrove@thesellingsource.com. Thank you.
					";
					
							
			$email_port = 25;
			$email_url = "sellingsource.com";
			$email_s_name = "DataGrubber";
			$email_s_address = "data-grubber-noreply@thesellingsource.com";
			
			// Build Email Header
			$header = new StdClass ();
			$header->smtp_server = $email_smtp_server;
			$header->port = $email_port;
			$header->url = $email_url;
			$header->subject = "Funded to Datran - ".date("m-d-Y",strtotime("-1 day"));
			$header->sender_name = $email_s_name;
			$header->sender_address = $email_s_address;
				
		//email delivery
		// Create the Mail Object and Send the Mail	
		include_once("prpc/client.php");
		$mail = new prpc_client("prpc://smtp.2.soapdataserver.com/smtp.1.php");
			
		// Key Line - Create the mailing (Name of mailing, headers, scheduled date, scheduled time) DO NOT USE SCHEDULING!!!
		$mailing_id = $mail->CreateMailing ("datagrubber_run", $header, NULL, NULL);
	
		$r = new StdClass();
		$r->name= "john h.";
		$r->type="to";
		$r->address="john.hargrove@thesellingsource.com";
		
		$recipients = array();
		$recipients[] = $r;
	
		if ( !DEBUGMODE )
		{
			$r = new StdClass();
			$r->type="to";
			$r->name="Brian R.";
			$r->address="brian.rauch@thesellingsource.com";
			$recipients[] = $r;
		}
		
		
		
		// Key Line - Add the package to the mailing (mailing_id, array of recipients, message, array of attachments)
		$package_id = $mail->AddPackage ($mailing_id, $recipients, $message, NULL);

		// Key Line - Tell the server to process the mailing (send all emails)
		$result = $mail->SendMail ($mailing_id);
	
		// Debug Code - Use if you want to see the soap stuff
		// print_r ($mail->__get_wire ());
		echo " ... Report Mailing Id: ".$mailing_id."
";
		echo " ... Result: ".$result."\n";
		echo " ... Recipients: 
";		

?>