<?php

	/***
	
	***/
	
	
	require_once('mysql.3.php');
	require_once('debug.1.php');
	require_once('error.2.php');
	
	$sql = new MySQL_3();
	$sql->connect(NULL, "selsds001", "sellingsource", "%selling\$_db", Debug_1::Trace_Code(__FILE__,__LINE__));
	
	
	$start = date("Y-m-d", strtotime("-1 day"));
	$end = date("Y-m-d");
	$yesterday = strtotime("-1 day");
	
	$accounts=array();
	
	$rs=$sql->query("olp_bb_visitor","
	
	SELECT  blackbox_post.*
FROM application
join blackbox_state using (application_id)
join blackbox_post using (application_id)
where application.created_date BETWEEN '$start' and '$end'
and blackbox_state.bb_cwf IS NOT NULL
and blackbox_post.winner='cwf'", Debug_1::Trace_Code(__FILE__,__LINE__));
	$csv = "\"SSN\"\n";
	while ( $row = $sql->Fetch_Object_Row($rs) )
	{
		$ssn = (object) unserialize($row->data_sent);
		$ssn = $ssn->ssn;	
		if ( strlen($ssn) != 0 )
		{	
			$accounts[] = $ssn;
			$csv .= "\"$ssn\"\n";
		
		}
		
	}

				$email_port = 25;
			$email_url = "sellingsource.com";
			$email_s_name = "DataGrubber";
			$email_s_address = "data-grubber-noreply@thesellingsource.com";
			
			// Build Email Header
			$header = new StdClass ();
			$header->smtp_server = $email_smtp_server;
			$header->port = $email_port;
			$header->url = $email_url;
			$header->subject = "Blackbox CWF SSN Report - ".date("m-d-Y",$yesterday);
			$header->sender_name = $email_s_name;
			$header->sender_address = $email_s_address;
		
					$message = new StdClass ();
					$message->text = "There are ".count($accounts)." records attached.  This is an automatic email generated by TSSDataGrubber; do not reply.  If you have any questions, please contact john.hargrove@thesellingsource.com. Thank you.";
					
					
				$attachment_csv = new StdClass ();
				$attachment_csv->name = "cwf_ssn_report_".date("m-d-Y",$yesterday).".csv";
				$attachment_csv->content = base64_encode($csv);
				$attachment_csv->content_type = "text/x-csv";
				$attachment_csv->content_length = strlen ($csv);
				$attachment_csv->encoded = TRUE;						
					
					
					  
					
		//email delivery
		// Create the Mail Object and Send the Mail	
		include_once("prpc/client.php");
		$mail = new prpc_client("prpc://smtp.2.soapdataserver.com/smtp.1.php");
			
		// Key Line - Create the mailing (Name of mailing, headers, scheduled date, scheduled time) DO NOT USE SCHEDULING!!!
		$mailing_id = $mail->CreateMailing ("datagrubber_run", $header, NULL, NULL);
	
		$recipients = array();
		
		$rec = new StdClass();
		$rec->type="To";
		$rec->address="john.hargrove@thesellingsource.com";
		$rec->name="john hargrove";
		$recipients[] = $rec;
		
		$rec = new StdClass();
		$rec->type="To";
		$rec->address="sunshiner@gmail.com";
		$rec->name="sunshiner";
		$recipients[] = $rec;
		
		
		$rec = new StdClass();
		$rec->type="To";
		$rec->address="sean.martin@thesellingsource.com";
		$rec->name="Sean Martin";
		$recipients[] = $rec;
		
		

		// Key Line - Add the package to the mailing (mailing_id, array of recipients, message, array of attachments)
		$package_id = $mail->AddPackage ($mailing_id, $recipients, $message, array($attachment_csv));

		// Key Line - Tell the server to process the mailing (send all emails)
		$result = $mail->SendMail ($mailing_id);
	
		// Debug Code - Use if you want to see the soap stuff
		// print_r ($mail->__get_wire ());
		echo " ... Mailing Id: ".$mailing_id."
";
		echo " ... Result: ".$result."\n";
		echo " ... Recipients: 
";	

					$message = new StdClass ();
					$message->text = "
					
					DataGrubber Run #0434		
					
					$results
					
					 This is an automatic email generated by TSSDataGrubber; do not reply.  If you have any questions, please contact john.hargrove@thesellingsource.com. Thank you.
					";
					


?>