<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="refresh" content="60">
<link href="/css/main.css" media="screen" rel="stylesheet" type="text/css">
<title>Vendor API Scrubber Monitor</title>
</head>
<body>
<h1>eCash Vendor API - Scrubber Monitor</h1>
<div class="content">
<table>
	<tr>
		<th>Server</th>
		<th>Module</th>
		<th>Status</th>
	</tr>
<?php
if (isset($statuses) && is_array($statuses))
{
	foreach ($statuses as $host => $status)
	{
		echo "<tr>";
		echo "<td rowspan=\"2\" class=\"host\">$host</td>";
		
		$module_html = array();
		
		foreach ($modules as $module)
		{
			$module_html[] = sprintf('<td class="%s">%s</td><td>%s</td>',
				isset($status[$module]) ? 'scrub_on' : 'scrub_off',
				$module,
				isset($status[$module]) ? $status[$module] : '&nbsp;'
			);
		}
		
		echo implode("</tr>\n<tr>", $module_html);
		echo '</tr>' . PHP_EOL;
	}
}
?>
</table>
</div>
</body>
</html>